---
settings:
  name: Astra Control Center
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: release-notes/whats-new.html
  versions:
  - version-number: '22.11'
    url: "/astra-control-center"
  - version-number: '22.08'
    url: "/astra-control-center-2208"
  - version-number: '22.04'
    url: "/astra-control-center-2204"
  - version-number: '21.12'
    url: "/astra-control-center-2112"
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos do Astra Control Center
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: concepts
  - section: use
  - section: rest-api
  - section: support
  - title: Versões anteriores
    url: "/acc-earlier-versions.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
